#
# General routines for loading, saving procedure state (eg ZEST)
#
# Uses opi.procedure.temp for loading and saving.
#
# Author: Andrew Turpin    (aturpin@unimelb.edu.au)
# Date: August 2012
#
# Copyright 2012 Andrew Turpin 
# This program is part of the OPI (http://perimetry.org/OPI).
# OPI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

##############################################
# Save a procedure to a file
# Input
#   states - as generated by ZEST.start, FT.start, etc.
#            Should be a list of lists with at least element 'name'.
#   filename - filename.
#   append - if TRUE, append to file, else only write this to the file.
# Returns
#   NULL
##############################################
opi.procedure.save <- function(stateList, filename, append=TRUE) {
    if (append) {
        opi.procedure.temp <- NULL
        if (file.exists(filename))
            load(filename)  
        opi.procedure.temp <- c(opi.procedure.temp, stateList)
        save(opi.procedure.temp, file=filename)
    } else {
        opi.procedure.temp <- stateList
        save(opi.procedure.temp, file=filename)
    }
}#opi.procedure.save

##############################################
# Load procedures from a file
# Input
#   filename - filename
# Returns
#   List of states that are in the file
##############################################
opi.procedure.load <- function(filename) {
    load(filename)
    return(opi.procedure.temp)
}#opi.procedure.save
